<?php

/**
 * Implements hook_views_api().
 */
function views_pivot_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_theme().
 */
function views_pivot_theme() {
  return array(
    'views_ui_style_plugin_pivot' => array(
      'render element' => 'form',
      'file' => 'views_pivot.theme.inc',
    ),
  );
}

/**
 * Implements hook_autoload_info().
 */
function views_pivot_autoload_info() {
  return array(
    'views_plugin_style_pivot' => 'views_plugin_style_pivot.inc',
  );
}
